### ISSUE TITLE
Split paginated/unpaginated model.get

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#18]
Current we do a `models.dataSets.get({paging: false, fields: {...}})` -> unpaginated objects, `models.dataSets.get({paging: true, fields: {...}})` -> paginated objects + pager.

This is powerful but over-complicates the signature of the method.  We should discuss an alternative. i.e., eplit: get/getAll. The alternative would be making the pager partial, which is not nice because on paginated mode it should be just there.

[BREAKING CHANGE]

**Comment by adrianq** [comment]
Moved to clickup
