### ISSUE TITLE
Add fields to organisationUnits

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#19]
Some models, like orgUnits, have extra fields. Add the generic infrastructure required so any models with those extra features are fully supported and typed. Two ways:

- Simply merging an interface from the model.
- On more complicated endpoints, add a custom class.

**Comment by SferaDev** [comment]
For the OrgUnitSelector in d2-ui-components we did use extra fields and it "just works" since the only thing that we currently lack here are the type definitions.

**Comment by tokland** [comment]
Duplicated: #42
