### ISSUE TITLE
Allow filter equal by boolean

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/d2-api#35]
Filter properties always use ``string``, I believe we should type-check according to the property being filtered (and accept ``boolean`` and ``enum`` values).

For example the following should be invalid:

```
filter: { dataDimension: { eq: "SUM" } }, // INVALID
filter: { dataDimension: { eq: "true" } }, // INVALID yet what we currently need
filter: { dataDimension: { eq: true" } }, // VALID

filter: { aggregationType: { eq: "SUMA" } }, // INVALID
filter: { aggregationType: { eq: 2 } }, // INVALID
filter: { aggregationType: { eq: "SUM" } }, // VALID
```

See https://github.com/EyeSeeTea/d2-api/blob/b779e8cd3e395107b3e9032a8702daa20269aede/src/api/common.ts#L43-L45

**Comment by adrianq** [comment]
Moved to clickup
