### ISSUE TITLE
Complete GET /api/metadata

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#39]
Currently, on `GET /api/metadata` we support `MODEL:field` and `MODEL:filter`, but there are some global options, check:

https://docs.dhis2.org/2.32/en/developer/html/dhis2_developer_manual_full.html#webapi_metadata_export

- [ ] `{global: {fields: {id: true}, filter: {id: {eq: 1}}} `.

**Comment by adrianq** [comment]
Moved to clickup
