### ISSUE TITLE
Implement endpoint /organisationUnits

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#42]
Most models are generic, but some of them have extra options/endpoints. Therefore, we should also implement custom code for them. That's the case of organisationUnits.

https://docs.dhis2.org/2.33/en/developer/html/webapi_organisation_units.html

- [ ] Implement general infrastructure to support custom models (same api.models.$name)
- [ ] Identify which models should be custom
- [ ] Implement custom api.models.organisationUnits

See https://github.com/EyeSeeTea/d2-ui-components/pull/153

**Comment by adrianq** [comment]
Moved to clickup
