### ISSUE TITLE
Refactor ApiResponse to use futures

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#50]
## Motivation

Promises have some well-known [shortcomings](https://dev.to/avaq/fluture-a-functional-alternative-to-promises-21b). Some of them:

 - A promise cannot be canceled.
 - A promise has an untyped error branch. As it happens with exceptions errors, it's type is always `any`.

## Alternatives

We want a fully typed async data/error (a Promise+Either abstraction, `Async<Error, Data>`, not `Promise<Data>`) with built-in cancellation support. Some available libraries:

- [Fluture](https://github.com/fluture-js/Fluture/wiki/Comparison-of-Future-Implementations#fluture)
- [Folktale](https://github.com/fluture-js/Fluture/wiki/Comparison-of-Future-Implementations#folktale)
- [FunTask](https://github.com/fluture-js/Fluture/wiki/Comparison-of-Future-Implementations#funtask])

Fluture has a clean code, a full-range of features, TS bindings and it's very well maintained. It uses a functional style that is slightly awkward to use in JS/TS, so we probably want to build our wrapper over it (`Future`).

Cons: We cannot use async/await any more, as they only work for normal promises. 

## Goals

- [ ] Ideally, old apps using `ApiResponse` should work without or with minimal change. Basically, they use `apiResponse.getData()` and less so `cancel` and `map`.
- [ ] For new apps, we would use the new `ApiResponse` as a future. Following clean architecture principles, we'd create an `AppResponse` type/class that wraps only what we need from that future (probably only a `run` method), and then use it in react components like this:

```
const [users, setUsers] = React.useState<User>();
React.useEffect(() => {
    const user$  = compositionRoot.users.ge);
    return user$.run(setUser, msg => snackbar.error(msg))
})
```

Following best-practices, we'd create a new hook that merges both features. Just an sketch:

```
type AsyncResponse<Data> =
    | { type: "loading" }
    | { type: "loaded"; data: Data }
    | { type: "error"; error: string };

const users: AsyncResponse<User> = useAsync(() => compositionRoot.users.get(), {
    onError: msg => snackbar.error(msg),
});
```

**Comment by tokland** [comment]
It's a matter of discussion if we can just leave D2ApiResponse as it, and the app would use a wrapper over futures. That certainly would do the migration very easy.

**Comment by adrianq** [comment]
Moved to clickup
