### ISSUE TITLE
Add missing data property to D2Access

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#53]
https://github.com/EyeSeeTea/d2-api/blob/master/src/schemas/base.ts#L9

Property `data: {read: boolean, write: boolean}` is missing for data schemas. 

Check that `schema.dataShareable` can be used to return normal/with-data D2Access for each model.

**Comment by SferaDev** [comment]
Yep noticed that a while back. Duplicate of https://github.com/EyeSeeTea/d2-api/issues/43 🤣

**Comment by tokland** [comment]
Oops :)
