### ISSUE TITLE
Add types for non-exposed internal classes in schemas

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-api#58]
Some references in the schemas point to classes used in dhis2-core but which are not exposed in the schema, so for the most part, are typed as `any` for now:

https://github.com/EyeSeeTea/d2-api/blob/feature/add-api-34/src/scripts/generate-schemas.ts#L48

How to solve it? Make it automatically parsed and versioned from the Java source code? (not trivial, but feasible, AFICS).

**Comment by adrianq** [comment]
Moved to clickup
